# Generated by Django 3.2.13 on 2022-08-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Man', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='contact',
            name='zip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='zip'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
    ]
